### ISSUE TITLE
truthiness code challenge

### ISSUE THREAD

**Issue by chanfe** [learn-co-curriculum/truthiness-code-challenge#28] opened 2018-07-20 17:37 UTC
I think that there is a bug that unable to select the provide check boxes.

**Comment by morgvanny** [comment] 2018-08-07 15:45
Hi! Thanks for letting us know. It seems the repository here is fine, so it should work generally - there may have been a particular bug having to do with learn.co. Usually refreshing, or moving to another lab and coming back to it will resolve it if you're using chrome. Otherwise, try using Ask A Question and we'll troubleshoot it with you. Sorry for the delayed response - hopefully this is helpful if it happens again.

**Closed as completed by morgvanny** 2018-08-07 15:45 UTC
Labels: Product

**Comment by namdevlife** [comment] 2019-03-06 06:24
Yes, the issue is still there as of now March 5th, 2018. But as morgavanny mentioned, you just need to refresh the browser. It will work as soon as you do so.
